### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by arden-metr** [erelayson/metr-training#1]
https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/helpers/dependent_form_helper.php#L61

You can also write it like this:
```
if ($param_value['is_required']) {
    $rules = 'required|'.$rules
}
```

May negative effect ba kung `required|` lang yung rule?

**Comment by arden-metr** [comment]
https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/helpers/dependent_form_helper.php#L71

Why do we have `post()` here?

**Comment by arden-metr** [comment]
https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/helpers/dependent_form_helper.php#L7

I think a better prefix is `DEPFORM_TYPE_`. E.g., `DEPFORM_TYPE_TEXTAREA`. Same with others.

**Comment by arden-metr** [comment]
https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/helpers/dependent_form_helper.php#L51

If I understand correctly, `data_type` is only for `type=list`?  If so, maybe a better name is `list_data_type`.

**Comment by arden-metr** [comment]
https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/helpers/dependent_form_helper.php#L131

`post('devices')` is hard-coded. Also, for `form_error()`, maybe we can just get the raw error message and let view deal with the actual presentation? (That is, no `<span>`.)

**Comment by arden-metr** [comment]
https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/helpers/dependent_form_helper.php#L157

Is this for `type=list`? Perhaps we can represent `3` as a constant (e.g., `DEPFORM_DEFAULT_CARDINALITY`) instead of hard-coding.

**Comment by arden-metr** [comment]
https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/helpers/dependent_form_helper.php#L160

Use defined type constants.

**Comment by arden-metr** [comment]
https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/helpers/dependent_form_helper.php#L3

I think a better prefix is `DEPFORM_SRCTYPE_`. E.g., `DEPFORM_SRCTYPE_MODEL`. Same with others.

**Comment by arden-metr** [comment]
https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/helpers/dependent_form_helper.php#L244

Add a constant for `10`.

**Comment by arden-metr** [comment]
https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/helpers/dependent_form_helper.php#L328

Unused function?

**Comment by arden-metr** [comment]
https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/controllers/Form.php#L147

Why are the `callback_()` validator functions here? Can't they be put inside helper?

**Comment by erelayson** [comment]
> 
> 
> https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/helpers/dependent_form_helper.php#L61
> 
> You can also write it like this:
> 
> ```
> if ($param_value['is_required']) {
>     $rules = 'required|'.$rules
> }
> ```
> 
> May negative effect ba kung `required|` lang yung rule?

Yes po. Pag may trailing pipe, ang nirereturn niya pong error is: "Unable to access an error message corresponding to your field name _____.()"

**Comment by erelayson** [comment]
> 
> 
> https://github.com/erelayson/metr-training/blob/9083bb07397ad37ee918a9b63322a1c34648d592/application/helpers/dependent_form_helper.php#L71
> 
> Why do we have `post()` here?

Ah coding error lang po. Same reason for all of its instances.

**Comment by erelayson** [comment]
[Added new validators to the Form Validation class (date, datetime, time, and password), and fixed a bug in the dependent_form_helper.php's rertrieve_error_messages function.](https://github.com/erelayson/metr-training/commit/e769735d23be74e87be19e8facb2515208bc86e3?branch=e769735d23be74e87be19e8facb2515208bc86e3&diff=split)


[ Fixed a bug in the date validator and set the validation error messages in the form_validation_lang config file.](https://github.com/erelayson/metr-training/commit/6e08fcaef06a33fb92de1d60ee19f28cca858249?branch=6e08fcaef06a33fb92de1d60ee19f28cca858249&diff=split)

**Comment by arden-metr** [comment]
Closing this issue. Everything is OK for now. Thanks @erelayson!
